# ------------------------------------------------------------------------------
# More resources related to this file:
# [1] Overview   | https://docs.docker.com/compose/
# [2] PostgreSQL | https://github.com/docker-library/docs/tree/master/postgres
# [3] Node.js    | https://github.com/nodejs/docker-node/blob/master/README.md#how-to-use-this-image
# -------------
#  More resources for your projects:
# [4] Samples    | https://github.com/docker/awesome-compose
# [5] Env Vars   | https://docs.docker.com/compose/environment-variables/
# [6] Secrets    | https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
# ------------------------------------------------------------------------------

  services:
    heroku-cli:
      build: ./heroku
      env_file: ./heroku/.env
  
    db:
      build: ./db
      env_file: .env
      volumes:
        - ./db/init_data:/docker-entrypoint-initdb.d
        - omdbapi-db-volume:/var/lib/postgresql/data  
      image: postgres
      # Environment variables to setup postgres. Note that this is not secure, and
      # in production (or your project), you should store these in a different
      # file [5] or use secrets [6]. In no case should such files be uploaded to GitHub.
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pwd
        POSTGRES_DB: OMDb_db
      expose:
        - "5432"                                  # We need only expose port `5432` internally to node (not the host)
  
    web:
      build: 
        context: ./
        dockerfile: Dockerfile
        target: devapp
      depends_on:
        - db                                      
      env_file: .env
      ports:
          - "3000:3000" 
      volumes:
        - ./src:/app/src
  
  volumes:
    omdbapi-db-volume: {}
  